# Generated by Django 4.0.5 on 2022-06-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0003_alter_ambiance_year'),
        ('authentication', '0002_alter_user_ambiance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ambiance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambiance.ambiance'),
            preserve_default=False,
        ),
    ]
