# Generated by Django 4.0.5 on 2022-06-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('code', models.CharField(max_length=20)),
                ('observations_trim1', models.TextField(blank=True, null=True)),
                ('observations_trim2', models.TextField(blank=True, null=True)),
                ('observations_trim3', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('ambiance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ambiance.ambiance')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
