# Generated by Django 4.0.5 on 2022-06-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('date_of_birth', models.DateField()),
                ('ambiance', models.CharField(choices=[('BOIS', 'Bois'), ('TERRE', 'Terre')], max_length=100)),
                ('reference_email', models.CharField(max_length=100)),
                ('reference_phone', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
