# Generated by Django 4.0.5 on 2022-06-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
