# Generated by Django 4.0.5 on 2022-06-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_six', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='langage',
            name='adjective',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'adjectif"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='adverb',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'adverbe"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='article',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'article"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='bass_clef',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La clé de Fa'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='box_objects_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="La 1ère boite d'objets"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='box_objects_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="La 2ème boite d'objets"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='conjunction',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La conjonction'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='design_shapes',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les formes à dessins'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='detective_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu du détective'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='farm',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La ferme'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='homophony_covers',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Les pochettes d'homophonies"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='img_after_read',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Images classifiées après lecture'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='img_before_read',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Images classifiées avant lecture'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='libraries',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Bibliothèques'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='logical_adjective_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Le jeu de l'adjectif logique"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='logical_adverb_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Le jeu de l'adverbe logique"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='logical_preposition_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu de la préposition logique'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='mobile_alphabets_1_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les alphabets mobiles 1 & 2'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='name_bells',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le nom des clochettes'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='nomenclature_before_read',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Nomenclature avant lecture'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='orders_123',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les ordres 1, 2, 3'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='preposition',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La préposition'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='question_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu des questions'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='read_different_media',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Lire : différents supports'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='read_sheet_music',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Lecture de partitions'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='read_write_music',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Lecture et écriture musicale'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='rough_letters_diagrams',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les lettres et diagrammes rugeux'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='sentence_analysis_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Analyse de la phrase, stade 1'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='sentence_analysis_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Analyse de la phrase, stade 2'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='sharp_flat',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Dièse et bémol'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='slates',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les ardoises'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='sound_analysis_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Le jeu d'analyse des sons"),
        ),
        migrations.AlterField(
            model_name='langage',
            name='stories_told',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Histoires racontées'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='verb',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le verbe : différents aspects'),
        ),
        migrations.AlterField(
            model_name='langage',
            name='write_different_media',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ecrire : différents supports'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_a',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='A'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_b',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='B'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_c',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='C'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_d',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='D'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_e',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='E'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_f',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='F'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_g',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='G'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_h',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='H'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_i',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='J'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_k',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='K'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_l',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='L'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_n',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_o',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='O'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_p',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='P'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_q',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='Q'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_r',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='R'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_s',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='S'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_t',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='T'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_u',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='U'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_v',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='V'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_w',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='W'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_x',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='X'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_y',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='Y'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_z',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='Z'),
        ),
        migrations.AlterField(
            model_name='math',
            name='add_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Addition statique / dynamique'),
        ),
        migrations.AlterField(
            model_name='math',
            name='add_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Le tableau de l'addition"),
        ),
        migrations.AlterField(
            model_name='math',
            name='bars_numbers',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Association barres et chiffres'),
        ),
        migrations.AlterField(
            model_name='math',
            name='chain_100',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La chaîne de 100'),
        ),
        migrations.AlterField(
            model_name='math',
            name='chain_1000',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La chaîne de 1000'),
        ),
        migrations.AlterField(
            model_name='math',
            name='chain_cube',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La chaîne du cube'),
        ),
        migrations.AlterField(
            model_name='math',
            name='chain_square',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La chaîne du carré'),
        ),
        migrations.AlterField(
            model_name='math',
            name='div_name',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les nommer'),
        ),
        migrations.AlterField(
            model_name='math',
            name='div_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Division statique / dynamique'),
        ),
        migrations.AlterField(
            model_name='math',
            name='div_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le tableau de la division'),
        ),
        migrations.AlterField(
            model_name='math',
            name='div_tube',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La grande division avec tubes'),
        ),
        migrations.AlterField(
            model_name='math',
            name='div_write',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les écrire'),
        ),
        migrations.AlterField(
            model_name='math',
            name='find_equivalences',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Rechercher les équivalences'),
        ),
        migrations.AlterField(
            model_name='math',
            name='hierarchies_quantity_symbol',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Hiérarchies : quantités, symboles, association'),
        ),
        migrations.AlterField(
            model_name='math',
            name='large_abacus',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Grand boulier : présentation'),
        ),
        migrations.AlterField(
            model_name='math',
            name='large_add_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Grand boulier : addition S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='large_multi_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Grand boulier : multiplication S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='large_sous_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Grand boulier : soustraction S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='little_abacus',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Petit boulier : présentation'),
        ),
        migrations.AlterField(
            model_name='math',
            name='little_abacus_add_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Petit boulier : addition S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='little_abacus_multi_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Petit boulier : MULTIPLICATION S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='little_abacus_sous_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Petit boulier : SOUSTRACTION S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='make_operations',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Faire des opérations'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memo_add_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Tables mémo addition 1, 2, 3, 4'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memo_div_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Tables mémo division 1, 2'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memo_multi',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Mémo multiplication : perles couleur'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memo_multi_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Tables mémo multiplication 1, 2, 3'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memo_sous_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Tables mémo soustraction 1, 2'),
        ),
        migrations.AlterField(
            model_name='math',
            name='memory_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu de mémoire'),
        ),
        migrations.AlterField(
            model_name='math',
            name='multi_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Multiplication statique / dynamique'),
        ),
        migrations.AlterField(
            model_name='math',
            name='multi_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le tableau de la multiplication'),
        ),
        migrations.AlterField(
            model_name='math',
            name='number_bars',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les barres numériques'),
        ),
        migrations.AlterField(
            model_name='math',
            name='points_tables',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La table des points'),
        ),
        migrations.AlterField(
            model_name='math',
            name='quantity_11_19',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='11 à 19 : les quantités'),
        ),
        migrations.AlterField(
            model_name='math',
            name='quantity_symbol_11_19',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='11 à 19 : asso quantités symboles'),
        ),
        migrations.AlterField(
            model_name='math',
            name='rough_numbers',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les chiffres rugeux'),
        ),
        migrations.AlterField(
            model_name='math',
            name='sd_number',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='SD : formation des grands nombres'),
        ),
        migrations.AlterField(
            model_name='math',
            name='sd_quantity',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='SD : 1ère présentation,  quantités'),
        ),
        migrations.AlterField(
            model_name='math',
            name='sd_symbol',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='SD : 1ère présentation, symboles'),
        ),
        migrations.AlterField(
            model_name='math',
            name='seguin_11_19',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='11 à 19 : la 1ère table de Seguin'),
        ),
        migrations.AlterField(
            model_name='math',
            name='seguin_11_99',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='11 à 99 : la 2ème table de Seguin'),
        ),
        migrations.AlterField(
            model_name='math',
            name='snake_game_add',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Le jeu du serpent de l'addition"),
        ),
        migrations.AlterField(
            model_name='math',
            name='snake_game_sous',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu du serpent de la soustraction'),
        ),
        migrations.AlterField(
            model_name='math',
            name='sous_sd',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Soustraction statique / dynamique'),
        ),
        migrations.AlterField(
            model_name='math',
            name='sous_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le tableau de la soustraction'),
        ),
        migrations.AlterField(
            model_name='math',
            name='spindles',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les fuseaux'),
        ),
        migrations.AlterField(
            model_name='math',
            name='stamps_add',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les timbres : addition S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='stamps_div',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les timbres : division S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='stamps_multi',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les timbres : multiplication S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='stamps_sous',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les timbres : soustraction S/D'),
        ),
        migrations.AlterField(
            model_name='math',
            name='token_game',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le jeu des jetons'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='Carry_tray',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Porter un plateau, un objet fragile'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='Carrying_mat',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Porter, dérouler et rouler un tapis'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='Screw_bolts',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Visser, dévisser des boulons'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='brush_carpet',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Brosser un tapis'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='carry_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Porter une table seul, à deux'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='chang_flower_water',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Changer l'eau des fleurs"),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='clean_mirror',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Nettoyer un miroir'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='cut_paper_scissors',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Couper du papier avec des ciseaux'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='dust',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Epousseter avec un chiffon, un plumeau'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='fold_fabrics',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Plier des étoffes'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='fold_paper',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Plier du papier'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_big_studs',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à gros boutons'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_lacing',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à laçage'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_loop',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à boucles'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_node',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à noeuds'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_press_studs',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à boutons pressions'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_safety_pin',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à épingles à nourrice'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_slide',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à glissière'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_small_studs',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à petits boutons'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='frame_staple',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cadre à agrafes'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='lesson_silence',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Leçon de silence'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='move_mood',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Se déplacer dans l'ambiance"),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='open_close_bottles',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ouvrir et fermer des flacons'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='open_close_boxes',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ouvrir et fermer des boites'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='open_close_door',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ouvrir et fermer une porte'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='open_close_padlock',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ouvir et fermer un cadenas'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='open_close_window',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Ouvrir et fermer une fenêtre, un tiroir'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='paste_paper',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Coller du papier'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='polish_brass',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Astiquer les cuivres'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='pour_rice',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Verser du riz'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='pour_sand',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Verser du sable'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='pour_water',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Verser de l'eau"),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='pour_water_glasses',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Verser de l'eau dans des verres"),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='sew',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Coudre'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='shine_shoes',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Cirer ses chaussures'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='squeeze_sponge',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Presser une éponge'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='sweep',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Balayer'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='take_care_plants',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Soigner les plantes'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='transfer_spoon',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Transvaser avec une cuillère'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='use_clothes_pegs',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Se servir depinces à linge'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='walk_line',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Marcher sur la ligne'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='wash_clothes',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Laver du linge'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='wash_hands',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Se laver les mains'),
        ),
        migrations.AlterField(
            model_name='practicallife',
            name='wash_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Laver la table'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='art',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Introduction à l'art"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='baryque_tablets',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les tablettes baryques'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='bells',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les clochettes'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='binomial_cube',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cube du binôme'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='botanical_maps',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cabinet de botaniques / cartes'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='botanical_tray',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cabinet de botaniques / plateau'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='brown_staircase',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'escalier marron"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='color_table_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les tables des couleurs 1'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='color_table_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les tables des couleurs 2'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='color_table_3',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les tables des couleurs 3'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='colored_cylinders',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les cylindres de couleur'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='colorful_globe',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le globe coloré'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 1'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 2'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_3',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 3'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_4',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 4'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_5',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 5'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='constructor_triangles_6',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les triangles constructeurs 6'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='cylindrical_sockets_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Emboitements cylindriques 1'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='cylindrical_sockets_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Emboitements cylindriques 2'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='cylindrical_sockets_3',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Emboitements cylindriques 3'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='cylindrical_sockets_4',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Emboitements cylindriques 4'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='electricity',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'électricité"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='europe',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="La carte de l'Europe"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='fabrics',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les étoffes'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='flags',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les drapeaux'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='flags_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les drapeaux : nomenclature classifiée'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='flavours',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les saveurs'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='geometric_solids',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les solides géométriques'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='geometry_drawers',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cabinet de géométrie / tiroirs'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='geometry_maps',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cabinet de géométrie / cartes'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='geometry_tray',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cabinet de géométrie / plateau'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='horizontal_water',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="l'eau qui s'équilibre sur un plan horizontal"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='land_water',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="Les contrastes de la terre et de l'eau"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='magnets_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les aimants 1'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='magnets_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les aimants 2'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='mystery_bag',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le sac à mystères'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='noise_boxes',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les boites à bruits'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='north',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La direction du nord'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='pink_tower',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La tour rose'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='planisphere',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le planisphère'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='puzzles_continents',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les puzzles des continents'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='pythagore_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='La table de Pythagore'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='red_bars',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les barres rouges'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='roman_arch',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'arche romane"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='seed_sorting',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le tri des graines'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='sink_float',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les objects qui coulent, qui flottent'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='smells',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les odeurs'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='smooth_rough',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Lisse et rugeux'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='smooth_rough_globe',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le globe lisse et rugeux'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='smooth_rough_table',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Lisse et rugeux : les tablettes'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='stereognostic_bag',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les sacs stéréognostiques'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='superimposed_figures',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les figures superposées'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='thermal_bottles',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les bouteilles thermiques'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='thermal_tablets',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Les tablettes thermiques'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='trinomial_cube',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name='Le cube du trinôme'),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='water_air_1',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'eau et l'air 1"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='water_air_2',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'eau et l'air 2"),
        ),
        migrations.AlterField(
            model_name='sensorymaterial',
            name='water_air_3',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ("En cours d'acquisition", "En cours d'acquisition"), ('Acquise', 'Acquise')], max_length=100, verbose_name="L'eau et l'air 3"),
        ),
    ]
