# Generated by Django 4.0.5 on 2022-06-27 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('three_six', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicallife',
            old_name='observations_pratique_1',
            new_name='observations_1',
        ),
        migrations.RenameField(
            model_name='practicallife',
            old_name='observations_pratique_2',
            new_name='observations_2',
        ),
        migrations.RenameField(
            model_name='practicallife',
            old_name='observations_pratique_3',
            new_name='observations_3',
        ),
    ]
