# Generated by Django 4.0.5 on 2022-06-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('three_six', '0002_alter_letter_letter_a_alter_letter_letter_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='letter_j',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], default=1, max_length=100, verbose_name='J'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='letter',
            name='letter_m',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], default=1, max_length=100, verbose_name='M'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_i',
            field=models.CharField(choices=[('Présentée', 'Présentée'), ('Entendue', 'Entendue'), ('Lue', 'Lue'), ('Ecrite', 'Ecrite')], max_length=100, verbose_name='I'),
        ),
    ]
