# Generated by Django 4.0.5 on 2022-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiance',
            name='name',
            field=models.CharField(choices=[('BOIS', 'Bois'), ('TERRE', 'Terre')], max_length=20, verbose_name='Ambiance'),
        ),
    ]
