# Generated by Django 4.0.5 on 2022-06-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambiance', '0002_alter_ambiance_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambiance',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Année'),
        ),
    ]
